# tasks/add_repo.yml
---
  - name: Add Kubernetes repository
    yum_repository:
      name: kubernetes
      description: Kubernetes Repository
      baseurl: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/rpm/"
      gpgcheck: yes
      gpgkey: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/rpm/repodata/repomd.xml.key"
      enabled: yes
      state: present
    when: ansible_os_family == "RedHat"
  - block:
      - name: Ensure the /etc/apt/keyrings directory exists
        file:
          path: /etc/apt/keyrings
          state: directory
          mode: '0755'

      - name: Download the Kubernetes APT key and save it
        ansible.builtin.get_url:
          url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
          dest: /tmp/kubernetes-apt-keyring.gpg
        register: download_result

      - name: Convert the downloaded key to GPG format
        ansible.builtin.command:
          cmd: gpg --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-apt-keyring.gpg
        when: download_result is success

      - name: Add Kubernetes APT repository to sources.list.d
        ansible.builtin.apt_repository:
          repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
          state: present

      - name: Remove temporary GPG file
        ansible.builtin.file:
          path: /tmp/kubernetes-apt-keyring.gpg
          state: absent

      - name: Update APT cache
        ansible.builtin.apt:
          update_cache: yes
    when: ansible_os_family == "Debian"